import { addDays, startOfWeek, format } from "date-fns";

const now = new Date();
const weekStart = startOfWeek(now, { weekStartsOn: 1 });

export const DEMO_REVIEWS = [
  {
    id: "demo-1",
    business_id: "demo",
    reviewer_name: "Ahmet Y.",
    rating: 1,
    text: "Berbat deneyim. Siparişim 2 saat geç geldi ve yemekler soğuktu. Bir daha asla gelmeyeceğim.",
    posted_at: new Date().toISOString(),
    status: "pending_reply",
    sentiment: "negative",
    summary: null,
    suggested_reply: null,
    approved_reply: null,
    replied_at: null,
    reply_source: null,
    google_review_id: null,
    google_review_name: null,
    google_reply_status: null,
    google_reply_error_message: null,
    issues: null,
    praises: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    business_id: "demo",
    reviewer_name: "Zeynep K.",
    rating: 2,
    text: "Beklentilerimi karşılamadı. Personel ilgisizdi ve fiyatlar çok yüksek.",
    posted_at: new Date().toISOString(),
    status: "pending_reply",
    sentiment: "negative",
    summary: null,
    suggested_reply: null,
    approved_reply: null,
    replied_at: null,
    reply_source: null,
    google_review_id: null,
    google_review_name: null,
    google_reply_status: null,
    google_reply_error_message: null,
    issues: null,
    praises: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    business_id: "demo",
    reviewer_name: "Mehmet S.",
    rating: 3,
    text: "Ortalama bir deneyim. Fiyat/performans uyumlu değil ama mekan güzel.",
    posted_at: addDays(now, -1).toISOString(),
    status: "pending_reply",
    sentiment: "neutral",
    summary: null,
    suggested_reply: null,
    approved_reply: null,
    replied_at: null,
    reply_source: null,
    google_review_id: null,
    google_review_name: null,
    google_reply_status: null,
    google_reply_error_message: null,
    issues: null,
    praises: null,
    created_at: addDays(now, -1).toISOString(),
  },
  {
    id: "demo-4",
    business_id: "demo",
    reviewer_name: "Elif D.",
    rating: 4,
    text: "Genel olarak memnun kaldım, sadece servis biraz yavaştı. Yemekler lezzetliydi.",
    posted_at: addDays(now, -2).toISOString(),
    status: "pending_reply",
    sentiment: "positive",
    summary: null,
    suggested_reply: null,
    approved_reply: null,
    replied_at: null,
    reply_source: null,
    google_review_id: null,
    google_review_name: null,
    google_reply_status: null,
    google_reply_error_message: null,
    issues: null,
    praises: null,
    created_at: addDays(now, -2).toISOString(),
  },
  {
    id: "demo-5",
    business_id: "demo",
    reviewer_name: "Can B.",
    rating: 5,
    text: "Harika! Hem yemekler hem servis mükemmeldi. Kesinlikle tekrar geleceğim.",
    posted_at: addDays(now, -3).toISOString(),
    status: "replied",
    sentiment: "positive",
    summary: null,
    suggested_reply: "Teşekkür ederiz Can Bey! Sizi tekrar ağırlamayı dört gözle bekliyoruz.",
    approved_reply: "Teşekkür ederiz Can Bey! Sizi tekrar ağırlamayı dört gözle bekliyoruz.",
    replied_at: addDays(now, -3).toISOString(),
    reply_source: "ai",
    google_review_id: null,
    google_review_name: null,
    google_reply_status: null,
    google_reply_error_message: null,
    issues: null,
    praises: null,
    created_at: addDays(now, -3).toISOString(),
  },
  {
    id: "demo-6",
    business_id: "demo",
    reviewer_name: "Selin T.",
    rating: 5,
    text: "Muhteşem atmosfer ve lezzetler. Arkadaşlarıma da tavsiye ettim!",
    posted_at: addDays(now, -4).toISOString(),
    status: "replied",
    sentiment: "positive",
    summary: null,
    suggested_reply: null,
    approved_reply: null,
    replied_at: null,
    reply_source: null,
    google_review_id: null,
    google_review_name: null,
    google_reply_status: null,
    google_reply_error_message: null,
    issues: null,
    praises: null,
    created_at: addDays(now, -4).toISOString(),
  },
  {
    id: "demo-7",
    business_id: "demo",
    reviewer_name: "Burak A.",
    rating: 4,
    text: "Güzel mekan, kahveleri harika. Tatlıları daha iyi olabilir.",
    posted_at: addDays(now, -5).toISOString(),
    status: "replied",
    sentiment: "positive",
    summary: null,
    suggested_reply: null,
    approved_reply: null,
    replied_at: null,
    reply_source: null,
    google_review_id: null,
    google_review_name: null,
    google_reply_status: null,
    google_reply_error_message: null,
    issues: null,
    praises: null,
    created_at: addDays(now, -5).toISOString(),
  },
];

export const DEMO_METRICS = {
  avgRating: "4.1",
  totalReviews: 156,
  reviewsThisWeek: 12,
  pendingReplies: 4,
};
